# Generated by Django 4.0.3 on 2022-04-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_follow_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
